"""add mixin in user table

Revision ID: 91e777fa2e04
Revises: eea622dc2096
Create Date: 2025-11-12 15:02:12.602429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91e777fa2e04'
down_revision: Union[str, Sequence[str], None] = 'eea622dc2096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_history', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medicine_intake_history', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_intake_history', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_intake_history', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('medicine_intake_history', 'recorded_at')
    op.add_column('medicine_schedules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_schedules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicine_schedules', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('medicines', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicines', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('medicines', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('medicines', 'dosage')
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users_info', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users_info', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users_info', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_info', 'deleted_at')
    op.drop_column('users_info', 'updated_at')
    op.drop_column('users_info', 'created_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.add_column('medicines', sa.Column('dosage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('medicines', 'deleted_at')
    op.drop_column('medicines', 'updated_at')
    op.drop_column('medicines', 'created_at')
    op.drop_column('medicine_schedules', 'deleted_at')
    op.drop_column('medicine_schedules', 'updated_at')
    op.drop_column('medicine_schedules', 'created_at')
    op.add_column('medicine_intake_history', sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('medicine_intake_history', 'deleted_at')
    op.drop_column('medicine_intake_history', 'updated_at')
    op.drop_column('medicine_intake_history', 'created_at')
    op.drop_column('medicine_history', 'deleted_at')
    op.drop_column('medicine_history', 'updated_at')
    op.drop_column('medicine_history', 'created_at')
    # ### end Alembic commands ###
