"""Add version table

Revision ID: d3f0d9b4547b
Revises: 91e777fa2e04
Create Date: 2025-11-12 17:07:56.619675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f0d9b4547b'
down_revision: Union[str, Sequence[str], None] = '91e777fa2e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_schedules_version',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('medicine_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('time_of_day', sa.Time(), autoincrement=False, nullable=True),
    sa.Column('dose_label', sa.String(), autoincrement=False, nullable=True),
    sa.Column('dosage', sa.String(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_medicine_schedules_version_end_transaction_id'), 'medicine_schedules_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_medicine_schedules_version_operation_type'), 'medicine_schedules_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_medicine_schedules_version_transaction_id'), 'medicine_schedules_version', ['transaction_id'], unique=False)
    op.create_table('medicines_version',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.String(), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_medicines_version_end_transaction_id'), 'medicines_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_medicines_version_operation_type'), 'medicines_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_medicines_version_transaction_id'), 'medicines_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_medicines_version_transaction_id'), table_name='medicines_version')
    op.drop_index(op.f('ix_medicines_version_operation_type'), table_name='medicines_version')
    op.drop_index(op.f('ix_medicines_version_end_transaction_id'), table_name='medicines_version')
    op.drop_table('medicines_version')
    op.drop_index(op.f('ix_medicine_schedules_version_transaction_id'), table_name='medicine_schedules_version')
    op.drop_index(op.f('ix_medicine_schedules_version_operation_type'), table_name='medicine_schedules_version')
    op.drop_index(op.f('ix_medicine_schedules_version_end_transaction_id'), table_name='medicine_schedules_version')
    op.drop_table('medicine_schedules_version')
    # ### end Alembic commands ###
